#!/bin/sh
# Load system configuration settings
#
### BEGIN INIT INFO
# Provides:          iothub
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $local_fs $syslog varserver createvars load
# Required-Stop:     $local_fs $syslog varserver createvars
# Short-Description: System Configuration loading
# Description:       Loads the system configuration (sysvar initialization)
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
DESC="IOTHUB Service"
NAME=iothub

if [ -f /usr/local/bin/"$NAME" ]; then
    IOTHUB=/usr/local/bin/iothub
else
    IOTHUB=/usr/bin/iothub
fi

if [ -f /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
fi

if [ -f /etc/init.d/functions ]; then
    . /etc/init.d/functions
fi

case "$1" in
start)  echo "Initializing IOTHub"
        $IOTHUB &
        ;;
restart) echo "Restarting $DESC" "$NAME"
        $0 start
        ;;
*)	echo "Usage: /etc/init.d/"$NAME" {start|restart}"
        exit 2
        ;;
esac
exit 0

