server.modules = (
    "mod_cgi",
    "mod_fastcgi"
)

server.document-root        = "/www/pages"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80


index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

fastcgi.debug = 1
fastcgi.server = (
  "/vars" => ((
    "bin-environment" => (
        "LD_LIBRARY_PATH" => "/usr/lib"
    ),
    "bin-path" => "/usr/bin/fcgi_vars",
    "socket" => "/tmp/fcgi_vars.sock",
    "check-local" => "disable",
    "max-procs" => 1,
  )),
  "/test" => ((
    "bin-environment" => (
        "LD_LIBRARY_PATH" => "/usr/lib"
    ),
    "bin-path" => "/usr/bin/fcgi_test",
    "socket" => "/tmp/fcgi_test.sock",
    "check-local" => "disable",
    "max-procs" => 1,
  ))
)


