require recipes-tgp-services/images/tgp-services-image.bb

DESCRIPTION = "The Gateway Project Core Components"

IMAGE_INSTALL += " libjson"
IMAGE_INSTALL += " libvarserver"
IMAGE_INSTALL += " libvarserver-dev"
IMAGE_INSTALL += " varserver"
IMAGE_INSTALL += " getvar"
IMAGE_INSTALL += " setvar"
IMAGE_INSTALL += " tcc"
IMAGE_INSTALL += " libtemplate"
IMAGE_INSTALL += " libvarcreate"
IMAGE_INSTALL += " libvmcore"
IMAGE_INSTALL += " libluavars"
IMAGE_INSTALL += " libvmasm"
IMAGE_INSTALL += " libvarvm-dev"
IMAGE_INSTALL += " varcreate"
IMAGE_INSTALL += " vartest"
IMAGE_INSTALL += " vasm"
IMAGE_INSTALL += " vexe"
IMAGE_INSTALL += " vm"
IMAGE_INSTALL += " print-template"
IMAGE_INSTALL += " tgp-corefs"
IMAGE_INSTALL += " execvars"
IMAGE_INSTALL += " filevars"
IMAGE_INSTALL += " fcgi-vars"
IMAGE_INSTALL += " fcgi-test"
IMAGE_INSTALL += " gpioctrl"
IMAGE_INSTALL += " iothub"
IMAGE_INSTALL += " iotsend"
IMAGE_INSTALL += " iotexec"

CORE_IMAGE_EXTRA_INSTALL += "packagegroup-cloud-azure"


